services:
  frontend:
    image: ghcr.io/adityaswaroop/aditya-app:client
    ports:
      - "3000:3000"
  backend:
    image: ghcr.io/adityaswaroop/aditya-app:server
    ports:
      - "4000:4000"
    env_file: ./server/.env